### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by ALMaclaine** [ALMaclaine/dart_spell#4]
The name spell is already taken:

https://pub.dev/packages/spell

I tried to get it transferred to us but they were not willing.

What other names do you think?

spell_checker is my next thought, but here are some suggestions from pub.dev:

"notypo", "textdebug", "detypo"  or "sans_typo"

**Comment by ahmetaa** [comment]
I will change to whatever you prefer.

**Comment by ALMaclaine** [comment]
Okay, I'll think it over and decide before publishing.

**Comment by ahmetaa** [comment]
By the way do you prefer complete transfer of the project? If it is possible I can do that.

**Comment by ALMaclaine** [comment]
It's up to you, you seem somewhat engaged in the process and you have expertise in language processing I don't have so I'm happy to keep you involved. If on the other hand you don't have much more time for this, then maybe perhaps it would be more efficient. Either way, upon publishing, both of us have to be verified to show up as contributors so that's also part of the decision.

**Comment by ahmetaa** [comment]
I had some non technical issues to follow, sorry for the very late response. I prefer transferring the ownership actually. Will do it shortly.

**Comment by ALMaclaine** [comment]
Okay sounds good, you're just going to transfer the github repo over to me?

**Comment by ALMaclaine** [comment]
It went through, thank you! Please stop by any time, appreciate your contributions.

**Comment by ahmetaa** [comment]
I appreciate all your work. Thanks. Life has become quite hectic for me, but  I will do what I can.
